### ISSUE TITLE
ItalicFont and BoldItalicFont aren't specified for sffamily, when option is chosen to assign Raleway to sffamily

### ISSUE THREAD

**Issue by jhanschoo** [silkeh/latex-raleway#1]
As mentioned in title. Will open a pull request that fixes this shortly.

edit: also c.f. https://groups.google.com/forum/#!topic/comp.text.tex/jm08c5s5IwU

**Comment by jhanschoo** [comment]
Resolve with #2

**Comment by silkeh** [comment]
Thanks for this! I'll create and upload a new release somewhere this week.

**Comment by jhanschoo** [comment]
Thanks!
